### ISSUE TITLE
Do you run this project?

### ISSUE THREAD

**Issue by vinhowe** [sully-h/DF_YT_project#1]
I am considering making a contribution to [DF Tube](https://chrome.google.com/webstore/detail/df-tube-distraction-free/mjdepdfccjgcndkmemponafgioodelna). I found this repository by doing a search for a string I found in the content script.

Is DF Tube your project? And would this be the right place to submit a PR—assuming you'd accept a contribution?

**Comment by sully-h** [comment]
Hi probably not: I cloned this project from someone else but haven't touched the code yet (I intend to make something quite different from it)

If I remember correctly: https://github.com/Shubham-Somani/Chrome-Extenstion-Youtube-Distraction-Free

was the original codebase. I will look again more closely later if you struggle to find it.

**Comment by vinhowe** [comment]
Okay. Thanks.
